# Generated by Django 3.0.2 on 2020-01-10 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/Books/img/', verbose_name='Image')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('state', models.CharField(max_length=256, verbose_name='State')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('neighbourhood', models.CharField(max_length=256, verbose_name='Neighbourhood')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('rel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
        ),
    ]
